"""
reporter/project_docs.py
------------------------
Auto-generates CLAUDE.md and agents.md in the project root.
These guide Claude Code and other agents when they open the project folder.
"""
from __future__ import annotations
from pathlib import Path
from datetime import date


CLAUDE_MD_TEMPLATE = """# Legal Knowledge Wiki — Project Context

> Auto-generated by legal-knowledge-wiki on {date}. Update manually as needed.

## What this project is

This is a legal knowledge base built from ingested legal documents (contracts,
regulations, playbooks, guidance notes). It uses Claude API to extract concepts,
map relationships, identify knowledge gaps, and generate wiki articles.

## Folder structure

| Folder | Contents |
|--------|----------|
| `sources/` | Raw input documents (PDF, DOCX, TXT, MD) |
| `wiki/` | Generated wiki — one markdown article per concept |
| `wiki/sources/` | Generated wiki — one page per source document |
| `concepts/` | JSON extractions of concepts per document |
| `connections/` | JSON of all cross-document connections |
| `gaps/` | Gap analysis JSON + gap_analysis.json |
| `output/` | HTML knowledge graph visualisation |
| `output/graph_prompts.md` | Ready-to-use Claude prompts from gap analysis |
| `todo/` | Prioritised to-do lists for knowledge development |
| `.infranodus/` | Ontology graph snapshots (living memory) |

## How to work with this project

**Ask me to:**
- "Summarise the main legal obligations in this knowledge base"
- "Find connections between [Concept A] and [Concept B]"
- "What are the biggest knowledge gaps?"
- "Generate a risk memo on [topic] based on the wiki"
- "Which source documents cover [regulation/topic]?"
- "Use the prompt in output/graph_prompts.md to bridge the gap between [X] and [Y]"

**Key concepts in this knowledge base ({n_concepts} total):**
{top_concepts}

**Active knowledge gaps:**
{top_gaps}

**To regenerate the graph after adding new sources:**
```bash
python main.py --mode all
```

**To regenerate only the graph (no API calls for wiki):**
```bash
python main.py --mode graph
```

## Important context for the AI agent

- All wiki articles use `[[wikilinks]]` for cross-referencing — treat these as concept links
- The `output/graph_prompts.md` file contains structured prompts designed to bridge specific gaps — use them as starting points for analysis
- The `.infranodus/ontology.json` file contains the current graph state — load it for structural context
- Source pages in `wiki/sources/` include "Gaps & Open Questions" sections — these are good entry points for research
- Concepts are typed: regulation, principle, obligation, right, risk, term, standard, entity
"""

AGENTS_MD_TEMPLATE = """# Agents Configuration

> Auto-generated by legal-knowledge-wiki on {date}.

## Available agents / modes

This project supports the following Claude Code workflows:

### 1. Research agent
**Goal:** Answer a legal question using the knowledge base
**How:** Ask any legal question. The agent will scan wiki/ and wiki/sources/,
identify relevant concepts, and synthesise an answer with citations.
**Best prompt:** "Based on the knowledge base, [legal question]? Reference specific wiki articles."

### 2. Gap bridge agent
**Goal:** Generate new legal insight by bridging knowledge gaps
**How:** Open `output/graph_prompts.md`. Copy a prompt. Paste into Claude Code terminal.
The prompt includes the graph structure so the agent reasons structurally, not just by retrieval.
**Best prompt:** Use verbatim prompts from graph_prompts.md

### 3. Ingestion agent
**Goal:** Add new sources and update the knowledge base
**How:** Drop new files into sources/ then run `python main.py --mode all`
**Note:** Previous extractions are preserved in concepts/; only new docs are processed

### 4. Wiki update agent
**Goal:** Expand or update a specific wiki article
**How:** "Update the wiki article for [[Concept Name]] to include [new information]"
**Note:** Edit the markdown file in wiki/ directly; run `python main.py --mode graph` to refresh graph

### 5. Memo generator agent
**Goal:** Draft a legal memo, risk assessment or clause recommendation
**How:** "Draft a risk memo on [topic] using the knowledge base as your source"
**Output:** A markdown memo that cites wiki articles and flags gaps

## Graph structure reference

The `.infranodus/ontology.json` contains:
- `nodes`: all concepts with type and importance
- `links`: all connections with relationship labels
- `gaps`: identified knowledge gaps
- `metadata`: generation date, source count, concept count

Load this file for structural context before generating analysis.

## Coding conventions

- All wiki articles: `wiki/[Concept_Name].md`
- All source pages: `wiki/sources/[Source_Name].md`
- Concept names: Title Case, 2-5 words
- Wikilinks: `[[Concept Name]]`
- Gap prompts: `output/graph_prompts.md`
- Ontology: `.infranodus/ontology.json`
"""

TODO_HEADER = """# Knowledge Development — To-Do

> Auto-generated from gap analysis on {date}. Update as you work.

"""


def write_claude_md(
    concepts: list[dict],
    gaps: dict,
    project_root: Path,
) -> None:
    """Write CLAUDE.md to project root."""
    top_concepts = "\n".join(
        f"- **{c['name']}** ({c.get('type', 'concept')}): {c.get('definition', '')[:70]}..."
        for c in sorted(concepts, key=lambda x: {"high": 3, "medium": 2, "low": 1}.get(x.get("importance", "low"), 1), reverse=True)[:15]
    )
    top_gaps = "\n".join(
        f"- {g.get('area', g.get('concept', 'Unknown'))}: {g.get('description', g.get('reason', ''))[:80]}"
        for g in (gaps.get("knowledge_gaps", []) + gaps.get("missing_definitions", []))[:5]
    ) or "- None identified in this run"

    content = CLAUDE_MD_TEMPLATE.format(
        date=date.today().isoformat(),
        n_concepts=len(concepts),
        top_concepts=top_concepts or "- Not yet extracted",
        top_gaps=top_gaps,
    )
    (project_root / "CLAUDE.md").write_text(content, encoding="utf-8")


def write_agents_md(project_root: Path) -> None:
    """Write agents.md to project root."""
    content = AGENTS_MD_TEMPLATE.format(date=date.today().isoformat())
    (project_root / "agents.md").write_text(content, encoding="utf-8")
